/// The unit of dispatch: a namespaced method call and its JSON, and the result it answers with.
///
/// [docs/architecture/protocol.md] §1.2 is the specification and it has one rule that shapes
/// this file: "params, result and data are **not** free-form maps… a method registry resolves it
/// into a generated DTO before any code touches it."
///
/// ## Why the typed registry is not here
///
/// §1.2 says the registry is a **generated** `switch` over method names, and
/// `plugins.md` §1 says the JSON codecs are generated by `freezed` and `json_serializable`.
/// Neither exists yet, and both are a later task's: a generated registry over method names that
/// do not exist yet would be a switch with one case, and generating it would put
/// `build_runner` config and a codegen dependency into the core for a file that declares no
/// methods.
///
/// So [MethodCall] carries [JsonMap] and is *deliberately* un-typed, in one direction only:
/// a [MethodCall] can only be built from JSON that arrived on the wire, and only a handler that
/// names a [JsonMap] can answer one. What is missing is the decode step, and §1.2's
/// `JsonDecoder`/`JsonEncoder` pair is where it lands. Until then the *wire* is typed — `JsonMap`
/// is a newtype over `Map<String, Object?>`, not `Map<String, dynamic>`, so `strict-casts`
/// applies inside every handler that receives one.
///
/// ## Why there is no `manifest` and no `AlteriOnePlugin` here
///
/// `plugins.md` §1's `AlteriOnePlugin` carries a `PluginManifest` getter and takes an
/// `AlteriOneRuntime`, and **neither of those types exists yet** — the manifest is task `0.29`
/// and the runtime is the capability handshake. Declaring the interface now would be declaring
/// two other tasks' declarations, which is the "written twice" failure this repository exists to
/// avoid, and the registry would then be coupled to a shape nobody has designed.
///
/// [MethodHandler] is the **narrow** contract dispatch actually needs, and a plugin satisfies
/// it by implementing a method it already has. `0.29` widens it to `AlteriOnePlugin` and adds
/// the manifest; nothing about the registry, the dispatcher or this file changes, because a
/// wider interface is assignable to a narrower one.
library;

import 'package:alteri_one_protocol/alteri_one_protocol.dart';

import 'namespace.dart';

/// A namespaced method call, with its parameters still in their wire form.
///
/// Immutable, and a value rather than a mutable request object: a call crosses a trust boundary
/// even when both sides are in the same isolate, and a value that cannot change after
/// construction cannot be changed by the handler it was handed to.
final class MethodCall {
  /// Creates a call to [method] with [params].
  ///
  /// The namespace and the operation are split here rather than by each handler, so a handler
  /// cannot disagree with the dispatcher about which namespace it was reached through — and
  /// `namespace` and `operation` are both read from the one [method] string, so there is no
  /// second field to fall out of step.
  ///
  /// **A method with no operation is refused.** `MethodNamespace.of` is a prefix match, so
  /// `core` parses to the `core` namespace; a call whose operation is empty is not a call, and
  /// accepting one would let a peer address a namespace rather than a method inside it.
  MethodCall(this.method, {this.params = JsonMap.empty})
    : namespace = _namespaceOf(method),
      operation = _operationOf(method) {
    if (operation.isEmpty) {
      throw ArgumentError.value(
        method,
        'method',
        'has no operation. A namespace is not a method: a peer addresses a method inside one, '
            'and a bare prefix would be a call to the namespace itself',
      );
    }
  }

  /// The full namespaced method: `core/run`, `$/cancelRequest`, `web/search`, `web.search`.
  final String method;

  /// The parameters, as they arrived. Typed per method by the generated registry, which is not
  /// here — see the library documentation.
  final JsonMap params;

  /// The namespace this call is routed by.
  final MethodNamespace namespace;

  /// Everything after the namespace and its separator: `run`, `cancelRequest`, `search`.
  ///
  /// For `core.initialize` — the one documented method spelled with a dot rather than a slash —
  /// the operation is `initialize`, because [namespace] has already consumed `core`.
  final String operation;

  @override
  String toString() => 'MethodCall($method)';

  @override
  bool operator ==(Object other) =>
      other is MethodCall && other.method == method && other.params == params;

  @override
  int get hashCode => Object.hash(method, params);
}

/// The namespace of [method], throwing for a method that does not begin with one.
///
/// A function rather than `MethodNamespace.of(method) ?? <something>` in the initializer list,
/// and the reason is what the `??` would have to be. A non-nullable `namespace` field cannot
/// come from a nullable parse, so the fallback would have to be *some* namespace — and the only
/// one available is `core`, which would route a malformed method to the engine's own handler and
/// answer it as though a peer had asked for a built-in. A method that cannot be parsed is a
/// `ArgumentError` at construction, which is `config.unknown_field` for a configuration value and
/// `-32600` for a frame, and neither of them is "the core, probably".
MethodNamespace _namespaceOf(String method) {
  final parsed = MethodNamespace.of(method);
  if (parsed == null) {
    throw ArgumentError.value(
      method,
      'method',
      'does not begin with a namespace. A method is `namespace` + a separator + an operation, '
          'and the namespace grammar is ${namespaceGrammar.pattern}',
    );
  }
  return parsed;
}

/// Everything after a namespace and its separator.
///
/// Both separators, and the reason is in [namespace]'s library documentation: the documents use
/// `/` for methods and topics and `.` for tool ids, plus `core.initialize` from the handshake,
/// and a method that failed to parse under one of them would route nowhere. The namespace has
/// already been consumed, so the first separator is the boundary.
String _operationOf(String method) {
  final dot = method.indexOf('.');
  final slash = method.indexOf('/');
  final cut = switch ((dot, slash)) {
    (-1, -1) => -1,
    (-1, final int s) => s,
    (final int d, -1) => d,
    (final int d, final int s) => d < s ? d : s,
  };
  return cut == -1 ? '' : method.substring(cut + 1);
}

/// What a handler answers a [MethodCall] with.
///
/// A newtype over [JsonMap] rather than the map itself, for the same reason the envelope's is: a
/// bare `Map<String, Object?>` is indistinguishable from every other map in the program, and
/// `strict-casts` is what stops a handler returning a `params` where a `result` was expected.
final class AlteriOneResult {
  /// Wraps [value] as a successful result.
  const AlteriOneResult(this.value);

  const AlteriOneResult._empty() : value = JsonMap.empty;

  /// An empty result, for a method whose answer is "done".
  ///
  /// A named constant rather than `const AlteriOneResult(JsonMap.empty)` at each call site,
  /// because "this method returns nothing" is a normal answer and spelling it as an empty
  /// literal invites a reader to wonder whether the fields were forgotten.
  static const AlteriOneResult empty = AlteriOneResult._empty();

  /// The result body.
  final JsonMap value;

  @override
  String toString() => 'AlteriOneResult($value)';

  @override
  bool operator ==(Object other) =>
      other is AlteriOneResult && other.value == value;

  @override
  int get hashCode => value.hashCode;
}

/// What the dispatcher needs from a bound unit.
///
/// The narrow contract, and [plugins.md] §1's `AlteriOnePlugin` is the wide one — it adds
/// `manifest`, `start`, `stop` and `events`. A plugin satisfies this by implementing a method it
/// already has, and the lifecycle arrives with the task that specifies the lifecycle.
///
/// **One member on purpose.** A dispatcher that could reach a plugin's lifecycle would be a
/// second thing that can start a unit, and `plugins.md` §2's sequence
/// (`discover → validate → bind → initialize → start → serve → stop`) is a *host* decision made
/// once, in one place, by the composition root. Everything the dispatcher needs to route a call
/// is a way to answer one.
abstract interface class MethodHandler {
  /// Answers [call].
  ///
  /// May throw: a handler that fails is the dispatcher's problem, not this interface's, and a
  /// `Result`-shaped return would put the question "what is a failure" into a type the protocol
  /// already answers — `AlteriOneError` and `-32603`.
  Future<AlteriOneResult> handle(MethodCall call);
}
