// The install page.
//
// This is the page most able to break a promise, because it is the page a reader arrives
// from a search result with the intention of running a command. Nothing is released: there
// is no install.sh in the tree, `alterione` is not on pub.dev, and every command printed
// here is labelled as the target shape before it is shown.
//
// The target is summarised from the "Installing" section of `README.md`,
// `docs/architecture/install-and-update.md`, `docs/architecture/build-and-release.md`,
// ADR-0016 and ADR-0017. Where a document shows a script, a layout or a table it is
// reproduced and attributed. Where none exists — an `alterione version` line, a doctor
// transcript — none is invented: a plausible-looking output block on a page like this is
// the one thing a reader has no way to check.

import 'package:jaspr/dom.dart';
import 'package:jaspr/jaspr.dart';

import '../components/ui.dart';
import '../content.dart';
import '../site.dart';

const String _heroTitle = 'A verified release — when there is one';

const String _heroLede =
    'The product is meant to be one directory: a compiled snapshot, a separately '
    'downloaded and digest-verified runtime, and a launcher you put on PATH. None of that '
    'exists yet. This page describes the shape the specification defines, and says '
    'plainly which parts of it are not there.';

/// `README.md`, verbatim, and quoted rather than paraphrased. It is the sentence the
/// project has already promised a reader, so rewording it here would create a second,
/// softer version of the same claim.
const String _statusQuote =
    'This is the target shape. Nothing is released yet, so neither command below works '
    'today — there is no install.sh in the tree and alterione is not on pub.dev. Both '
    'arrive with tasks 0.30 and 0.31.';

const String _targetCommands = r'''
sh install.sh                                   # no toolchain required
# or, if you have Dart:
dart pub global activate alterione && alterione install
''';

/// The normative layout from `install-and-update.md` §2. The home page carries the short
/// form of the same tree; this is the longer one, because the two extra lines — the
/// manifest and the installer — are what the verification section below is about.
const String _installRoot = r'''
~/.alterione/                        # $ALTERIONE_HOME, default ~/.alterione
├── alterione                        # launcher — executable, add this directory to PATH
├── alterione-update                 # update
├── install.sh | install.ps1 | install.cmd
├── alterione.aot                    # the compiled release
├── alterione.yaml                   # the shipped manifest: runtime, api, extensions
├── manifest.json                    # versions, SHA-256 digests, signatures
├── bin/
│   └── dartrantime                  # the pinned AOT runtime, downloaded at install time
├── apps/                            # mirrors the source subprojects
│   └── cli/
├── tools/                           # Tier 2 tool executables and Tier 0 data
├── injections/                      # Tier 0 skill packs, Tier 2 injection executables
├── plugins/                         # Tier 2 plugin executables
├── config/                          # profiles/, policies.d/, config.yaml
├── state/                           # runtime state
└── logs/
''';

const String _launcher = r'''
#!/bin/sh
# alterione — generated by the installer. Runs the compiled release on the pinned runtime.
set -eu
home=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
[ -n "${ALTERIONE_HOME:-}" ] && home="$ALTERIONE_HOME"
exec "$home/bin/dartrantime" "$home/alterione.aot" "$@"
''';

/// The launch-time checks from `install-and-update.md` §5, as (subject, what is checked,
/// refusal). A table rather than cards because the reader's question is "which check does
/// my exit code come from", and that question is answered by comparing two columns.
const List<(String, String, String)> _launchChecks = <(String, String, String)>[
  (
    'bin/dartrantime',
    'present, and its digest matches manifest.json',
    'exit 9 · integrity.integrity_failed',
  ),
  (
    'dartrantime',
    'version inside runtime.version',
    'exit 9 · integrity.runtime_mismatch',
  ),
  (
    'alterione.aot',
    'digest matches the signed manifest',
    'exit 9 · integrity.integrity_failed',
  ),
  (
    'alterione.yaml',
    'parses, and its apiVersion is known',
    'exit 3 · config.unknown_api_version',
  ),
  (
    'extensions',
    'every enabled entry resolves in the compiled registry',
    'exit 3 · extension.unresolved',
  ),
  (
    'api.*',
    'every extension is inside api.extension, each port inside api.ports',
    'exit 3 · extension.version_incompatible',
  ),
];

const List<(String, String, String)> _namingRows = <(String, String, String)>[
  ('Workspace root', 'alteri_one/', 'alterione/ — ~/.alterione'),
  (
    'Library packages',
    'alteri_one_core, alteri_one_protocol, …',
    'compiled into alterione.aot',
  ),
  (
    'Extension packages',
    'alteri_one_tool_fs, alteri_one_plugin_mcp, …',
    'compiled in, or deployed under tools/, plugins/',
  ),
  ('Launcher', 'tool/install/ templates', 'alterione, executable, on PATH'),
  (
    'Dart runtime',
    'the developer SDK on the machine',
    'bin/dartrantime, downloaded and verified',
  ),
];

/// A bordered data table. Local to this page rather than part of `ui.dart` because the
/// two uses have different column counts and different column semantics — one is check to
/// refusal, the other is source to product — and a shared helper for two unrelated shapes
/// would be a helper for neither.
Component _table(
  List<String> headers,
  List<List<Component>> rows,
) => div(classes: 'overflow-x-auto rounded-xl border border-line', [
  table(classes: 'w-full min-w-[38rem] border-collapse text-left', [
    thead([
      for (final header in headers)
        th(
          classes:
              'bg-canvas-subtle px-5 py-3 font-mono text-xs tracking-[0.14em] '
              'text-ink-muted uppercase',
          [.text(header)],
        ),
    ]),
    tbody(classes: 'divide-y divide-line', [
      for (final row in rows)
        tr([
          for (final cell in row) td(classes: 'px-5 py-4 align-top', [cell]),
        ]),
    ]),
  ]),
]);

class InstallPage extends StatelessComponent {
  const InstallPage({super.key});

  @override
  Component build(BuildContext context) {
    return SitePage(
      title: 'Install',
      path: Routes.install,
      lede: _heroLede,
      summary:
          'How an AlteriOne release is meant to be installed: an AOT snapshot on a pinned, '
          'digest-verified runtime under ~/.alterione, verified before it runs. Nothing is '
          'released yet.',
      child: div([
        _hero(),
        _status(),
        _root(),
        _verification(),
        _paths(),
        _naming(),
        _today(),
        _close(),
      ]),
    );
  }
}

Component _hero() =>
    section(classes: 'brand-wash paper-grid border-b border-line', [
      div(classes: container, [
        div(classes: 'py-20 sm:py-28', [
          eyebrow('Installing'),
          h1(
            classes: 'mt-7 max-w-4xl text-4xl font-semibold tracking-tight text-balance sm:text-6xl',
            [.text(_heroTitle)],
          ),
          p(classes: 'mt-6 max-w-2xl text-lg text-pretty text-ink-muted', [
            .text(_heroLede),
          ]),
          div(classes: 'mt-9 flex flex-wrap items-center gap-3', [
            buttonLink(
              doc('architecture/install-and-update.md'),
              'The install specification',
              external: true,
              primary: true,
              icon: '↗',
            ),
            buttonLink(Routes.documentation, 'Documentation'),
          ]),
        ]),
      ]),
    ]);

/// The status band, deliberately before anything else. A reader who has to scroll to find
/// out that the install commands do not work yet has already been misled by the first
/// screen.
Component _status() => section(classes: 'border-b border-line bg-surface', [
  div(classes: container, [
    div(
      classes: 'flex flex-col gap-4 py-8 sm:flex-row sm:items-center sm:gap-8',
      [
        span(
          classes:
              'inline-flex w-fit shrink-0 items-center gap-2 rounded-full border '
              'border-line px-3 py-1 font-mono text-xs tracking-[0.14em] uppercase',
          [
            span(classes: 'h-1.5 w-1.5 rounded-full bg-accent', const []),
            span(classes: 'text-ink', [.text('Nothing released')]),
          ],
        ),
        p(classes: 'max-w-3xl text-sm text-pretty text-ink-muted', [
          span(classes: 'text-ink', [.text(_statusQuote)]),
          .text(' '),
          externalLink(
            doc('process/task-breakdown.md'),
            [.text('The task breakdown is public')],
            classes: 'text-ink-muted underline decoration-line underline-offset-4 hover:text-ink',
          ),
          .text(', so you can see exactly what exists and what does not.'),
        ]),
      ],
    ),
    div(classes: 'pb-8', [
      codeBlock(
        _targetCommands,
        caption: 'Target shape — neither command works today',
      ),
    ]),
  ]),
]);

Component _root() => section(classes: 'py-20 sm:py-24', [
  div(classes: container, [
    sectionHeading(
      'One directory, verified before it runs',
      eyebrow: 'The install root',
      lede:
          'Everything the user receives is named alterione. The four subproject '
          'directories mirror the source tree, so a reader opening ~/.alterione/tools/fs/ '
          'is looking at the same kind of thing as tools/fs/ in the repository, and every '
          'deployed extension has one place to live and one digest record.',
    ),
    div(classes: 'mt-10 grid gap-8 lg:grid-cols-5', [
      div(classes: 'lg:col-span-3', [codeBlock(_installRoot)]),
      div(classes: 'lg:col-span-2', [
        div(classes: 'prose', [
          p([
            .text(
              'The launcher is the whole installation story: it is named alterione so that '
              'adding the install root to PATH is all there is to do. It resolves its own '
              'directory, so it works from anywhere, and it honours ALTERIONE_HOME when '
              'that is set.',
            ),
          ]),
          p([
            .text(
              'The runtime it executes is not the Dart SDK. It carries no pub, no compiler '
              'and no development tooling, because those are exactly the capabilities an '
              'untrusted Tier 2 child must never inherit.',
            ),
          ]),
          p([
            .text(
              'The decision, and why a snapshot was split from its runtime, is ',
            ),
            externalLink(doc('decisions/0017-aot-snapshot-and-runtime.md'), [
              .text('ADR-0017'),
            ]),
            .text('.'),
          ]),
        ]),
      ]),
    ]),
    div(classes: 'mt-10', [
      codeBlock(_launcher, caption: 'The launcher, in full'),
    ]),
  ]),
]);

Component _verification() =>
    section(classes: 'border-y border-line bg-canvas-subtle py-20 sm:py-24', [
      div(classes: container, [
        sectionHeading(
          'Six steps, and no check that has a weaker outcome',
          eyebrow: 'Verification',
          lede:
              'Both installation paths run the same six steps in the same order over the '
              'same release manifest. A failure at any step leaves the previous installation '
              'byte-for-byte unchanged, and installing twice re-verifies rather than '
              'accumulating files.',
        ),
        div(classes: 'mt-10 grid gap-8 lg:grid-cols-5', [
          div(classes: 'lg:col-span-2', [
            codeBlock(
              'resolve target\nfetch manifest\nverify signature\nstage\nverify digests\nswap',
              caption: 'The six install steps',
            ),
          ]),
          div(classes: 'prose lg:col-span-3', [
            p([
              .text(
                'The manifest is the root of trust and the release signature covers it: '
                'manifest.json carries the versions and the SHA-256 digests of alterione.aot, '
                'alterione.yaml and bin/dartrantime. A missing or unverifiable signature '
                'stops the install before a single byte is written.',
              ),
            ]),
            p([
              .text(
                'No check degrades. A missing, stale or unverified runtime never falls back '
                'to a system dart, to JIT or to running from source — a JIT fallback would '
                'silently remove the property the whole tier model rests on. alterione doctor '
                'performs the same checks on demand, and alterione which reports the install '
                'root, the release version, the runtime version and the digests it verified.',
              ),
            ]),
          ]),
        ]),
        div(classes: 'mt-12', [
          _table(
            <String>['Checked when the launcher starts', 'Refused with'],
            [
              for (final (subject, detail, refusal) in _launchChecks)
                <Component>[
                  div(classes: 'flex flex-col gap-1.5', [
                    code(classes: 'inline-code', [.text(subject)]),
                    span(classes: 'text-sm text-ink-muted', [.text(detail)]),
                  ]),
                  span(
                    classes: 'font-mono text-xs leading-relaxed text-ink-muted',
                    [.text(refusal)],
                  ),
                ],
            ],
          ),
        ]),
        p(classes: 'mt-8 max-w-3xl text-sm text-ink-muted', [
          .text(
            'The verification order, the atomicity rule and the failure behaviour are ',
          ),
          externalLink(doc('architecture/install-and-update.md'), [
            .text('install-and-update.md §4 and §5'),
          ]),
          .text('; the check list behind doctor is in '),
          externalLink(doc('architecture/observability.md'), [
            .text('observability.md §7'),
          ]),
          .text('.'),
        ]),
      ]),
    ]);

Component _paths() => section(classes: 'py-20 sm:py-24', [
  div(classes: container, [
    sectionHeading(
      'A shell installer and a bootstrap on pub.dev',
      eyebrow: 'Two front ends',
      lede:
          'Both do the same six steps over the same manifest, and the shell scripts are '
          'generated translations of the bootstrap plan rather than a second implementation '
          'that can drift. The release pipeline asserts that they produce an identical file '
          'set for the same release.',
    ),
    div(classes: 'mt-10 grid gap-5 sm:grid-cols-2', [
      card(
        [
          p(classes: 'mt-3 text-sm text-ink', [
            .text('A POSIX shell, PowerShell or cmd.'),
          ]),
          p(classes: 'mt-3 text-sm text-ink-muted', [
            code(classes: 'inline-code', [.text('sh install.sh')]),
            .text(', '),
            code(classes: 'inline-code', [.text('pwsh install.ps1')]),
            .text(' or '),
            code(classes: 'inline-code', [.text('install.cmd')]),
            .text(
              '. The script never requires elevation; a system-wide install is a choice made '
              'by passing a directory, and the default is a user directory.',
            ),
          ]),
        ],
        kicker: 'Path one',
        title: 'Shell installer',
      ),
      card(
        [
          p(classes: 'mt-3 text-sm text-ink', [.text('A Dart SDK.')]),
          p(classes: 'mt-3 text-sm text-ink-muted', [
            code(classes: 'inline-code', [
              .text('dart pub global activate alterione'),
            ]),
            .text(' and then '),
            code(classes: 'inline-code', [.text('alterione install')]),
            .text(
              '. It never executes extension code, never runs the release during an '
              'installation, and never reaches an origin other than the release host.',
            ),
          ]),
        ],
        kicker: 'Path two',
        title: 'Bootstrap CLI',
      ),
    ]),
    div(classes: 'mt-10 grid gap-8 lg:grid-cols-5', [
      div(classes: 'prose lg:col-span-3', [
        p([
          .text(
            'Every flag is optional: an install directory, a channel of stable or beta, an '
            'exact version that is mutually exclusive with a channel, a target triple, '
            'skipping the runtime for an offline copy that already has one, and a force '
            'flag that reinstalls over an existing tree — still atomic, still verified.',
          ),
        ]),
        p([
          .text(
            'Uninstalling removes the release, the runtime and the deployed '
            'extension payloads, and keeps config/ and state/ unless a purge flag is '
            'given — and the purge prints exactly what it will delete before it does. '
            'That state is the transcripts, memories and profiles that belong to the '
            'user.',
          ),
        ]),
      ]),
      div(classes: 'lg:col-span-2', [
        callout('An install reaches exactly one origin', [
          p([
            .text(
              'The release host named on the command line. There is no analytics call, no '
              'crash report and no version ping, and the third north-star goal is zero bytes '
              'of telemetry unless it is explicitly opted into.',
            ),
          ]),
          p([
            .text('Specified in '),
            externalLink(doc('architecture/install-and-update.md'), [
              .text('install-and-update.md §1'),
            ]),
            .text('; the flag tables are in §4.'),
          ]),
        ]),
      ]),
    ]),
  ]),
]);

Component
_naming() => section(classes: 'border-y border-line bg-surface py-20 sm:py-24', [
  div(classes: container, [
    sectionHeading(
      'One word for the user, one convention for the code',
      eyebrow: 'Naming',
      lede:
          'Two names are in play for one product, and the rule is one sentence: inside the '
          'source tree Dart convention applies and the packages are alteri_one_*; '
          'everything the user receives is alterione.',
    ),
    div(classes: 'mt-10', [
      _table(
        <String>['Thing', 'In the source tree', 'In the installed product'],
        [
          for (final (thing, source, product) in _namingRows)
            <Component>[
              span(classes: 'text-sm font-medium text-ink', [.text(thing)]),
              span(
                classes: 'font-mono text-xs leading-relaxed text-ink-muted',
                [.text(source)],
              ),
              span(
                classes: 'font-mono text-xs leading-relaxed text-ink-muted',
                [.text(product)],
              ),
            ],
        ],
      ),
    ]),
    div(classes: 'mt-8 prose', [
      p([
        .text(
          'The boundary is kept honest by tests rather than by review, because a naming '
          'rule nobody checks decays within a release. Task 0.31 fails the release '
          'assembly if the string alteri_one appears in any installed path, in the '
          'launcher or update script, in the manifest payload or in a default '
          'configuration value.',
        ),
      ]),
      p([
        .text(
          'The decision, and the bootstrap package that is the one deliberate '
          'exception, is ',
        ),
        externalLink(doc('decisions/0016-product-naming.md'), [
          .text('ADR-0016'),
        ]),
        .text('.'),
      ]),
    ]),
  ]),
]);

/// Single column: the steps are a numbered list and a table of cards at site width would
/// put three items a reader reads in sequence onto one row.
Component _today() => section(classes: 'py-20 sm:py-24', [
  div(classes: measure, [
    sectionHeading(
      'What you can actually do today',
      eyebrow: 'Today',
      lede:
          'There is nothing to install, and the specification is the part worth reading. It '
          'is public, it is link-checked, and it is version-controlled alongside the code '
          'it describes.',
    ),
    div(classes: 'mt-8 prose', [
      ol([
        li([
          strong([.text('Read it. ')]),
          .text(
            'The documentation index states the reading order, and the first two entries '
            'are not interchangeable: concepts.md fixes what a tool, an injection, a plugin, '
            'a capability and an app each mean, and the rest of the tree relies on those '
            'words.',
          ),
        ]),
        li([
          strong([.text('Clone it and resolve. ')]),
          .text(
            'The repository is a Melos workspace with pub workspaces; dart pub get at the '
            'root resolves every package in it, and melos run analyze, melos run test and '
            'melos run format are the gates a change has to pass.',
          ),
        ]),
        li([
          strong([.text('Watch the work. ')]),
          .text(
            'The task breakdown gives every task a stable id and one automated acceptance '
            'criterion, so you can tell what exists from what is planned without reading '
            'the issue tracker.',
          ),
        ]),
      ]),
    ]),
    div(classes: 'mt-8', [
      callout('Security reports', [
        p([
          .text(
            'Do not open a public issue for a vulnerability. GitHub Security Advisories is '
            'the preferred channel; the policy, the severity table, the disclosure deadlines '
            'and the trust boundaries a report may rely on are in ',
          ),
          externalLink(repositoryFile('SECURITY.md'), [.text('SECURITY.md')]),
          .text(', and published advisories are on the '),
          externalLink('$repository/security/advisories', [
            .text('security advisories page'),
          ]),
          .text('.'),
        ]),
      ]),
    ]),
  ]),
]);

Component _close() => section(classes: 'border-t border-line py-20 sm:py-24', [
  div(classes: container, [
    div(
      classes: 'rounded-2xl border border-line bg-canvas-subtle px-6 py-12 sm:px-12 sm:py-16',
      [
        div(classes: 'max-w-2xl', [
          eyebrow('In the meantime'),
          h2(
            classes: 'mt-3 text-2xl font-semibold tracking-tight text-balance sm:text-3xl',
            [
              .text(
                'Follow the specification. It is the part of this project that is finished.',
              ),
            ],
          ),
          p(classes: 'mt-4 text-base text-pretty text-ink-muted', [
            .text(
              'This page summarises the install design and links onward; it does not '
              'replace it. Where this page and the specification disagree, the '
              'specification is right and this page is out of date.',
            ),
          ]),
          div(classes: 'mt-8 flex flex-wrap items-center gap-3', [
            buttonLink(
              doc('architecture/install-and-update.md'),
              'Installation and update',
              external: true,
              primary: true,
              icon: '↗',
            ),
            buttonLink(
              doc('README.md'),
              'The specification',
              external: true,
              icon: '↗',
            ),
            buttonLink(Routes.documentation, 'Documentation'),
          ]),
        ]),
      ],
    ),
  ]),
]);
